In [1]:
pip install gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (5.2.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown) (3.29.0)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown) (4.67.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2026.4.22)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (1.7.1)

In [2]:
import re
import gdown
import os
import numpy as np
import pandas as pd
import torch
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoModelForTokenClassification

In [3]:
os.makedirs("ate_gate_teacher_phase1", exist_ok=True)
os.makedirs("ate_teacher_phase1", exist_ok=True)

In [15]:
gate_model_path = "/content/ate_gate_teacher_phase1"
ate_model_path = "/content/ate_teacher_phase1"
data_path = "/content/split_3.5.parquet"

In [5]:
gdown.download_folder(id = "1llFWPucByC0w4cYbikcEVI8jSByjSaGT",output = gate_model_path)
gdown.download_folder(id = "1myRmGAF-81bIzE-XNW610VEvdNBQ2Ptx",output = ate_model_path)

Retrieving folder contents

Processing file 1ASYoP9aeasSiE8nCg5OxN1orK8XymgcH best_train_loss.json
Processing file 1iYzPM6bCTB4HC3nhbFMHyI6fPVsKlF0_ config.json
Processing file 1ckc7iQAl0O6msFVyA9Fx_cuAZd2AWuBt model.safetensors
Processing file 17erW6MxZ2R1hmLwRdKVzppUDCLnPEOwT tokenizer_config.json
Processing file 1vHVIgps9ksO0AKmkxw4a61P1GrgBcOfH tokenizer.json
Processing file 1sxqwgf3uqb6v3fpicHYsxNMfdNCkj_M7 training_args.bin

Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=1ASYoP9aeasSiE8nCg5OxN1orK8XymgcH
To: /content/ate_gate_teacher_phase1/best_train_loss.json
100%|██████████| 69.0/69.0 [00:00<00:00, 269kB/s]
Downloading...
From: https://drive.google.com/uc?id=1iYzPM6bCTB4HC3nhbFMHyI6fPVsKlF0_
To: /content/ate_gate_teacher_phase1/config.json
100%|██████████| 865/865 [00:00<00:00, 1.73MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1ckc7iQAl0O6msFVyA9Fx_cuAZd2AWuBt
From (redirected): https://drive.google.com/uc?id=1ckc7iQAl0O6msFVyA9Fx_cuAZd2AWuBt&confirm=t&uuid=3d4c7be3-4016-44aa-8f90-d22126c5ba19
To: /content/ate_gate_teacher_phase1/model.safetensors
100%|██████████| 499M/499M [00:02<00:00, 206MB/s]
Downloading...
From: https://drive.google.com/uc?id=17erW6MxZ2R1hmLwRdKVzppUDCLnPEOwT
To: /content/ate_gate_teacher_phase1/tokenizer_config.json
100%|██████████| 359/359 [00:00<00:00, 1.43MB/s]
Downloading...
From: https://drive.google.com/uc?id=1vHVIgps9ksO0AKmkxw4a61P1GrgBcOfH
To: /content/ate_gate_teacher_phase1/tokenizer.json
100%|██████████| 3.56M/3.56M [00:00<00:00, 10.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1sxqwgf3uqb6v3fpicHYsxNMfdNCkj_M7
To: /content/ate_gate_teacher_phase1/training_args.bin
100%|██████████| 5.20k/5.20k [00:00<00:00, 16.2MB/s]
Download completed
Retrieving folder contents

Retrieving folder 1_t6pTZv_eHrGu8Nm38hyL9pOcsDzuPqj checkpoint-228
Processing file 122G9aDqj6VNeF5IeNKKuRmtm0kj6KcNK config.json
Processing file 1gxSLeRxp9lZkO2dbRXWaY19Rp5D07suk model.safetensors
Processing file 1fO43gVr1tfk3i3s05smNr1iAasjvIPgS optimizer.pt
Processing file 1kIqlc-sMssaBVvnvAQLUHMIHf_w-se-c rng_state.pth
Processing file 12N93sHc1zyoiw6t-6NrykFsVZkV9ymKU scaler.pt
Processing file 1mTb1RRwP-lLdYfu-kG_kVtTaBA95KpLD scheduler.pt
Processing file 1iwm7k42bUCGeRyb-s-pSAicOgElJgK-F tokenizer_config.json
Processing file 1r4tcuZY6JjLJr4gWcpl8353ylB7twZ8z tokenizer.json
Processing file 1kZZI_scofhsiv5uQjPuNUIfO49SXguhk trainer_state.json
Processing file 1Mlsk5qYUlIr3k6GZQOQcOgZd2b0FYqZS training_args.bin
Retrieving folder 1NJ2xrX400cFIi3SmpM-aUXwIDS5XlS6f checkpoint-342
Processing file 1DlXvS0uGcb6WM4fqst_AplRfT7paz402 config.json
Processing file 10rCf0U6LwQhiCFDkPTVLkwszE0fvjojs model.safetensors
Processing file 1I0Yf9LJAXzTIASc-qsvoOUB3UgRz8xLN optimizer.pt
Processing file 1OdIODwsqGmcJF5hYajGaYJVwxz3qQkxo rng_state.pth
Processing file 1hSpskgk5weNZ-uTN8EXfkDrR7v-oaG_b scaler.pt
Processing file 1JNkbS-jR_xgpm5BDPWZKZuDFkdSIcl3W scheduler.pt
Processing file 1FRVEWF9Y-mGPEr3RhJu9pGLjjctZV5ea tokenizer_config.json
Processing file 1xUh3oiyNaEiatPlywg5Z8WbMb18m-z9R tokenizer.json
Processing file 11Q-K1M74N7S58aD91lHUSLtGoIef3lvk trainer_state.json
Processing file 1JeKivrtJ4sqm_TuPLVPRsS9ZpNnmNGoW training_args.bin
Processing file 1g8239JIiTqMB7NjbM_N-TIur2IaSq7yF best_train_loss.json
Processing file 1wB6lJyfqIb887qvTe3TAFdP51gdXjtIc config.json
Processing file 1G1mzxXzDXfGNl-2rBJdihf6f8BMSnilL model.safetensors
Processing file 1J7YthuhQ4lA4Kd55DJ8rMPlStd2g3Uo- tokenizer_config.json
Processing file 10Ld1EGyYRUMREQv-Oz1rTkXF748tV60j tokenizer.json

Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=122G9aDqj6VNeF5IeNKKuRmtm0kj6KcNK
To: /content/ate_teacher_phase1/checkpoint-228/config.json
100%|██████████| 821/821 [00:00<00:00, 3.83MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1gxSLeRxp9lZkO2dbRXWaY19Rp5D07suk
From (redirected): https://drive.google.com/uc?id=1gxSLeRxp9lZkO2dbRXWaY19Rp5D07suk&confirm=t&uuid=6f6a5abb-e78f-47ef-943d-c20f6ffdb377
To: /content/ate_teacher_phase1/checkpoint-228/model.safetensors
100%|██████████| 496M/496M [00:02<00:00, 220MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1fO43gVr1tfk3i3s05smNr1iAasjvIPgS
From (redirected): https://drive.google.com/uc?id=1fO43gVr1tfk3i3s05smNr1iAasjvIPgS&confirm=t&uuid=1df639cb-c456-4809-b458-22e8baeffb61
To: /content/ate_teacher_phase1/checkpoint-228/optimizer.pt
100%|██████████| 993M/993M [00:10<00:00, 98.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1kIqlc-sMssaBVvnvAQLUHMIHf_w-se-c
To: /content/ate_teacher_phase1/checkpoint-228/rng_state.pth
100%|██████████| 14.6k/14.6k [00:00<00:00, 32.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=12N93sHc1zyoiw6t-6NrykFsVZkV9ymKU
To: /content/ate_teacher_phase1/checkpoint-228/scaler.pt
100%|██████████| 1.38k/1.38k [00:00<00:00, 4.90MB/s]
Downloading...
From: https://drive.google.com/uc?id=1mTb1RRwP-lLdYfu-kG_kVtTaBA95KpLD
To: /content/ate_teacher_phase1/checkpoint-228/scheduler.pt
100%|██████████| 1.47k/1.47k [00:00<00:00, 6.45MB/s]
Downloading...
From: https://drive.google.com/uc?id=1iwm7k42bUCGeRyb-s-pSAicOgElJgK-F
To: /content/ate_teacher_phase1/checkpoint-228/tokenizer_config.json
100%|██████████| 359/359 [00:00<00:00, 1.62MB/s]
Downloading...
From: https://drive.google.com/uc?id=1r4tcuZY6JjLJr4gWcpl8353ylB7twZ8z
To: /content/ate_teacher_phase1/checkpoint-228/tokenizer.json
100%|██████████| 3.56M/3.56M [00:00<00:00, 196MB/s]
Downloading...
From: https://drive.google.com/uc?id=1kZZI_scofhsiv5uQjPuNUIfO49SXguhk
To: /content/ate_teacher_phase1/checkpoint-228/trainer_state.json
100%|██████████| 1.50k/1.50k [00:00<00:00, 1.27MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Mlsk5qYUlIr3k6GZQOQcOgZd2b0FYqZS
To: /content/ate_teacher_phase1/checkpoint-228/training_args.bin
100%|██████████| 5.20k/5.20k [00:00<00:00, 16.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1DlXvS0uGcb6WM4fqst_AplRfT7paz402
To: /content/ate_teacher_phase1/checkpoint-342/config.json
100%|██████████| 821/821 [00:00<00:00, 4.09MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=10rCf0U6LwQhiCFDkPTVLkwszE0fvjojs
From (redirected): https://drive.google.com/uc?id=10rCf0U6LwQhiCFDkPTVLkwszE0fvjojs&confirm=t&uuid=dccd26fa-7e48-40da-a12b-721b8810c5a3
To: /content/ate_teacher_phase1/checkpoint-342/model.safetensors
100%|██████████| 496M/496M [00:02<00:00, 247MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1I0Yf9LJAXzTIASc-qsvoOUB3UgRz8xLN
From (redirected): https://drive.google.com/uc?id=1I0Yf9LJAXzTIASc-qsvoOUB3UgRz8xLN&confirm=t&uuid=5a6674be-ea1b-4f31-b10a-66133b3b5541
To: /content/ate_teacher_phase1/checkpoint-342/optimizer.pt
100%|██████████| 993M/993M [00:04<00:00, 232MB/s]
Downloading...
From: https://drive.google.com/uc?id=1OdIODwsqGmcJF5hYajGaYJVwxz3qQkxo
To: /content/ate_teacher_phase1/checkpoint-342/rng_state.pth
100%|██████████| 14.6k/14.6k [00:00<00:00, 26.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1hSpskgk5weNZ-uTN8EXfkDrR7v-oaG_b
To: /content/ate_teacher_phase1/checkpoint-342/scaler.pt
100%|██████████| 1.38k/1.38k [00:00<00:00, 2.67MB/s]
Downloading...
From: https://drive.google.com/uc?id=1JNkbS-jR_xgpm5BDPWZKZuDFkdSIcl3W
To: /content/ate_teacher_phase1/checkpoint-342/scheduler.pt
100%|██████████| 1.47k/1.47k [00:00<00:00, 4.80MB/s]
Downloading...
From: https://drive.google.com/uc?id=1FRVEWF9Y-mGPEr3RhJu9pGLjjctZV5ea
To: /content/ate_teacher_phase1/checkpoint-342/tokenizer_config.json
100%|██████████| 359/359 [00:00<00:00, 1.40MB/s]
Downloading...
From: https://drive.google.com/uc?id=1xUh3oiyNaEiatPlywg5Z8WbMb18m-z9R
To: /content/ate_teacher_phase1/checkpoint-342/tokenizer.json
100%|██████████| 3.56M/3.56M [00:00<00:00, 223MB/s]
Downloading...
From: https://drive.google.com/uc?id=11Q-K1M74N7S58aD91lHUSLtGoIef3lvk
To: /content/ate_teacher_phase1/checkpoint-342/trainer_state.json
100%|██████████| 1.87k/1.87k [00:00<00:00, 9.01MB/s]
Downloading...
From: https://drive.google.com/uc?id=1JeKivrtJ4sqm_TuPLVPRsS9ZpNnmNGoW
To: /content/ate_teacher_phase1/checkpoint-342/training_args.bin
100%|██████████| 5.20k/5.20k [00:00<00:00, 14.2MB/s]
Downloading...
From: https://drive.google.com/uc?id=1g8239JIiTqMB7NjbM_N-TIur2IaSq7yF
To: /content/ate_teacher_phase1/best_train_loss.json
100%|██████████| 95.0/95.0 [00:00<00:00, 189kB/s]
Downloading...
From: https://drive.google.com/uc?id=1wB6lJyfqIb887qvTe3TAFdP51gdXjtIc
To: /content/ate_teacher_phase1/config.json
100%|██████████| 821/821 [00:00<00:00, 3.18MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1G1mzxXzDXfGNl-2rBJdihf6f8BMSnilL
From (redirected): https://drive.google.com/uc?id=1G1mzxXzDXfGNl-2rBJdihf6f8BMSnilL&confirm=t&uuid=dfbe2d44-7fb4-4837-b306-ceeab884b1b0
To: /content/ate_teacher_phase1/model.safetensors
100%|██████████| 496M/496M [00:05<00:00, 83.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1J7YthuhQ4lA4Kd55DJ8rMPlStd2g3Uo-
To: /content/ate_teacher_phase1/tokenizer_config.json
100%|██████████| 359/359 [00:00<00:00, 1.28MB/s]
Downloading...
From: https://drive.google.com/uc?id=10Ld1EGyYRUMREQv-Oz1rTkXF748tV60j
To: /content/ate_teacher_phase1/tokenizer.json
100%|██████████| 3.56M/3.56M [00:00<00:00, 235MB/s]
Download completed

['/content/ate_teacher_phase1/checkpoint-228/config.json',
 '/content/ate_teacher_phase1/checkpoint-228/model.safetensors',
 '/content/ate_teacher_phase1/checkpoint-228/optimizer.pt',
 '/content/ate_teacher_phase1/checkpoint-228/rng_state.pth',
 '/content/ate_teacher_phase1/checkpoint-228/scaler.pt',
 '/content/ate_teacher_phase1/checkpoint-228/scheduler.pt',
 '/content/ate_teacher_phase1/checkpoint-228/tokenizer_config.json',
 '/content/ate_teacher_phase1/checkpoint-228/tokenizer.json',
 '/content/ate_teacher_phase1/checkpoint-228/trainer_state.json',
 '/content/ate_teacher_phase1/checkpoint-228/training_args.bin',
 '/content/ate_teacher_phase1/checkpoint-342/config.json',
 '/content/ate_teacher_phase1/checkpoint-342/model.safetensors',
 '/content/ate_teacher_phase1/checkpoint-342/optimizer.pt',
 '/content/ate_teacher_phase1/checkpoint-342/rng_state.pth',
 '/content/ate_teacher_phase1/checkpoint-342/scaler.pt',
 '/content/ate_teacher_phase1/checkpoint-342/scheduler.pt',
 '/content/ate_teacher_phase1/checkpoint-342/tokenizer_config.json',
 '/content/ate_teacher_phase1/checkpoint-342/tokenizer.json',
 '/content/ate_teacher_phase1/checkpoint-342/trainer_state.json',
 '/content/ate_teacher_phase1/checkpoint-342/training_args.bin',
 '/content/ate_teacher_phase1/best_train_loss.json',
 '/content/ate_teacher_phase1/config.json',
 '/content/ate_teacher_phase1/model.safetensors',
 '/content/ate_teacher_phase1/tokenizer_config.json',
 '/content/ate_teacher_phase1/tokenizer.json']

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"

gate_tokenizer = AutoTokenizer.from_pretrained(gate_model_path, use_fast=True)
gate_model = AutoModelForSequenceClassification.from_pretrained(gate_model_path).to(device)
gate_model.eval()

ate_tokenizer = AutoTokenizer.from_pretrained(ate_model_path, use_fast=True)
ate_model = AutoModelForTokenClassification.from_pretrained(ate_model_path).to(device)
ate_model.eval()

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

RobertaForTokenClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-11): 12 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): RobertaIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): RobertaOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=3, bias=True)
)

In [7]:
df = pd.read_parquet(data_path)
df

,parent_asin,review_id,sentence_id,sentence_text,rating
0,B07VC9NCQN,B07VC9NCQN,1055,getting real tired of having all the repeats j...,5.0
1,B00I0WHVZW,B00I0WHVZW,610,we purchased this app a few [GENERIC_NOUN] ago...,5.0
2,B07FTXNXCF,B07FTXNXCF,122,excellent excellent [GENERIC_NOUN] to do worko...,5.0
3,B000HCZ8EO,B000HCZ8EO,77,br certainly not [DOMAIN_NOISE] [GENERIC_NOUN]...,1.0
4,B01N0BP507,B01N0BP507,2245,five [GENERIC_NOUN] works perfect,5.0
...,...,...,...,...,...
994698,B01LXOU5PM,B01LXOU5PM,1739,does not work on fire this app does not work o...,1.0
994699,B000077DD8,B000077DD8,146,of course youll have the ser and estar verbs d...,1.0
994700,B017Y5QV2Y,B017Y5QV2Y,163,watch on app my 3 yr old loves blippi,5.0
994701,B017JEVTP4,B017JEVTP4,1455,please fix the app,2.0
994702,B00BUR9KJE,B00BUR9KJE,51,the game would be five [GENERIC_NOUN] if the d...,2.0

In [8]:
TOKEN_RE = re.compile(r"\b\w+(?:'\w+)?\b")

def clean_text(text):
    if pd.isna(text):
        return ""
    text = str(text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

def tokenize_words(text):
    return [m.group(0) for m in TOKEN_RE.finditer(text)]

def normalize_span(span):
    span = clean_text(span)
    span = re.sub(r"\s+", " ", span)
    return span.strip(" \t\n\r.,;:!?()[]{}\"'")

In [ ]:
def decode_bio_spans(tokens, labels, confidences):
    """
    Decode BIO labels thành aspect spans.
    confidence của span = mean confidence của token trong span.
    """
    spans = []
    i = 0

    while i < len(labels):
        if labels[i] == "B-ASP":
            start = i
            i += 1

            while i < len(labels) and labels[i] == "I-ASP":
                i += 1

            end = i - 1
            text = normalize_span(" ".join(tokens[start:end + 1]))

            if text:
                conf = float(np.mean(confidences[start:end + 1]))
                spans.append({
                    "aspect": text,
                    "confidence": conf,
                    "start_token": start,
                    "end_token": end,
                })
        else:
            i += 1

    # Deduplicate theo aspect text, giữ confidence cao nhất
    best = {}
    for span in spans:
        key = span["aspect"]
        if key not in best or span["confidence"] > best[key]["confidence"]:
            best[key] = span

    return sorted(best.values(), key=lambda x: (-x["confidence"], x["aspect"]))

def predict_gate_proba(sentences, batch_size=64, max_length=192):
    probs_all = []

    for i in range(0, len(sentences), batch_size):
        batch = sentences[i:i + batch_size]

        enc = gate_tokenizer(
            batch,
            truncation=True,
            max_length=max_length,
            padding=True,
            return_tensors="pt",
        ).to(device)

        with torch.no_grad():
            logits = gate_model(**enc).logits
            probs = torch.softmax(logits, dim=-1)[:, 1].detach().cpu().numpy()

        probs_all.extend(probs.tolist())

    return probs_all

def predict_ate_one(sentence, max_length=192):
    tokens = tokenize_words(sentence)

    if not tokens:
        return {
            "tokens": [],
            "labels": [],
            "token_confidences": [],
            "spans": [],
        }

    enc = ate_tokenizer(
        tokens,
        is_split_into_words=True,
        truncation=True,
        max_length=max_length,
        return_tensors="pt",
    )

    word_ids = enc.word_ids()
    enc = {k: v.to(device) for k, v in enc.items()}

    with torch.no_grad():
        logits = ate_model(**enc).logits[0]
        probs = torch.softmax(logits, dim=-1).detach().cpu().numpy()
        pred_ids = probs.argmax(axis=-1)

    id2label = ate_model.config.id2label

    word_labels = ["O"] * len(tokens)
    word_confidences = [0.0] * len(tokens)

    seen_word_ids = set()

    for token_idx, word_id in enumerate(word_ids):
        if word_id is None or word_id in seen_word_ids:
            continue

        seen_word_ids.add(word_id)

        pred_id = int(pred_ids[token_idx])
        label = id2label[pred_id]
        conf = float(probs[token_idx, pred_id])

        word_labels[word_id] = label
        word_confidences[word_id] = conf

    spans = decode_bio_spans(tokens, word_labels, word_confidences)

    return {
        "tokens": tokens,
        "labels": word_labels,
        "token_confidences": word_confidences,
        "spans": spans,
    }

def predict_aspects(
    texts,
    gate_threshold=0.90,
    span_threshold=0.90,
    gate_batch_size=64,
    max_length=192,
    return_debug=False,
):
    """
    Input:
        texts: str

    Output:
        DataFrame gồm:
        - sentence
        - gate_confidence
        - aspects
        - confidences

    Logic:
        Nếu gate p(has_aspect) < gate_threshold -> aspects = []
        Nếu gate qua threshold -> chạy ATE, giữ span có confidence >= span_threshold
    """
    single_input = isinstance(texts, str)

    if single_input:
        sentences = [clean_text(texts)]
    else:
        sentences = [clean_text(x) for x in texts]

    gate_probs = predict_gate_proba(
        sentences,
        batch_size=gate_batch_size,
        max_length=max_length,
    )

    rows = []

    for sentence, gate_p in zip(sentences, gate_probs):
        if gate_p < gate_threshold:
            row = {
                "sentence": sentence,
                "gate_confidence": float(gate_p),
                "aspects": [],
                "confidences": [],
            }

            if return_debug:
                row.update({
                    "tokens": [],
                    "labels": [],
                    "token_confidences": [],
                    "raw_spans": [],
                })

            rows.append(row)
            continue

        ate_pred = predict_ate_one(sentence, max_length=max_length)

        kept_spans = [
            span for span in ate_pred["spans"]
            if span["confidence"] >= span_threshold
        ]

        row = {
            "sentence": sentence,
            "gate_confidence": float(gate_p),
            "aspects": [x["aspect"] for x in kept_spans],
            "confidences": [x["confidence"] for x in kept_spans],
        }

        if return_debug:
            row.update({
                "tokens": ate_pred["tokens"],
                "labels": ate_pred["labels"],
                "token_confidences": ate_pred["token_confidences"],
                "raw_spans": ate_pred["spans"],
            })

        rows.append(row)

    result_df = pd.DataFrame(rows)

    return result_df

In [ ]:
def process_file(df, output_dir,category_name):
    sentences = df["sentence_text"].tolist()

    results = []
    batch_size = 32

    print("Running model...")
    for i in tqdm(range(0, len(sentences), batch_size)):
        batch = sentences[i:i + batch_size]

        preds = predict_aspects(
            batch,
            gate_threshold=0.9,
            span_threshold=0.85,
        )

        results.append(preds)

    result_df = pd.concat(results, ignore_index=True)

    df = pd.concat([df.reset_index(drop=True), result_df], axis=1)

    def is_high(row):
        gate = row["gate_confidence"]
        aspects = row["aspects"]

        if gate <= 0.1:
            return True

        if gate >= 0.9 and len(aspects) > 0:
            return True

        return False

    high_df = df[df.apply(is_high, axis=1)].copy()
    low_df = df[~df.apply(is_high, axis=1)].copy()

    high_df["category_name"] = "Software"

    high_df = high_df[
        [
            "parent_asin",
            "sentence_id",
            "sentence_text",
            "rating",
            "category_name",
            "gate_confidence",
            "aspects",
            "confidences",
        ]
    ]

    low_df = low_df[
        [
            "parent_asin",
            "sentence_id",
            "sentence_text",
            "rating",
            "gate_confidence",
        ]
    ]

    os.makedirs(output_dir, exist_ok=True)
    os.makedirs("outputs/reports/ate_1", exist_ok=True)

    high_path = f"{output_dir}/high_confidence_samples_{category_name}.parquet"
    low_path = f"{output_dir}/low_confidence_samples_{category_name}.parquet"

    high_df.to_parquet(high_path, index=False)
    low_df.to_parquet(low_path, index=False)

    print(f"Saved HIGH → {high_path} ({len(high_df)})")
    print(f"Saved LOW  → {low_path} ({len(low_df)})")

    total_samples = len(high_df)

    if total_samples == 0:
        has_aspect_ratio = 0
        total_aspects = 0
        avg_aspect_per_sample = 0
    else:
        has_aspect_count = high_df["aspects"].apply(lambda x: len(x) > 0).sum()
        has_aspect_ratio = has_aspect_count / total_samples

        total_aspects = high_df["aspects"].apply(len).sum()
        avg_aspect_per_sample = total_aspects / total_samples

    report_path = f"outputs/reports/ate_1/ate_1_report_{category_name}.txt"

    with open(report_path, "w") as f:
        f.write(f"Category: {category_name}\n")
        f.write(f"Total high confidence samples: {total_samples}\n")
        f.write(f"Has aspect ratio: {has_aspect_ratio:.4f}\n")
        f.write(f"Total aspects: {total_aspects}\n")
        f.write(f"Average aspects per sample: {avg_aspect_per_sample:.4f}\n")

    print(f"Saved REPORT → {report_path}")

In [12]:
CATEGORY_NAME = "Software"
output = "/content/output/"
process_file(df,output,CATEGORY_NAME)

Running model...

100%|██████████| 31085/31085 [2:04:38<00:00,  4.16it/s]

Saved HIGH → /content/output//high_confidence_samples_Software.parquet (761601)
Saved LOW  → /content/output//low_confidence_samples_Software.parquet (233102)
Saved REPORT → outputs/reports/ate_1/ate_1_report_Software.txt

In [14]:
df_data = pd.read_parquet("/content/output/high_confidence_samples_Software.parquet")
df_data

,parent_asin,sentence_id,sentence_text,rating,category_name,gate_confidence,aspects,confidences
0,B000HCZ8EO,77,br certainly not [DOMAIN_NOISE] [GENERIC_NOUN]...,1.0,Software,0.007501,[],[]
1,B01N0BP507,2245,five [GENERIC_NOUN] works perfect,5.0,Software,0.024119,[],[]
2,B009KS4XRO,1345,their live chat service agents use pretyped co...,1.0,Software,0.971061,[live chat service agents],[0.9133308976888657]
3,B00JU7EPSW,135,now for the good [GENERIC_NOUN] this game is a...,4.0,Software,0.992717,"[game, music]","[0.990712583065033, 0.9233402609825134]"
4,B004X74ZG6,39,it seems that the [DOMAIN_NOISE] android marke...,1.0,Software,0.944044,[android marketplace],[0.8962448835372925]
...,...,...,...,...,...,...,...,...
761596,B006HJKKCG,735,actually speaks the words,5.0,Software,0.006586,[],[]
761597,B0051HRMNU,53,cool this app is really useful,5.0,Software,0.984674,[app],[0.9943851232528687]
761598,B01LXOU5PM,1739,does not work on fire this app does not work o...,1.0,Software,0.987768,[app],[0.9814614653587341]
761599,B000077DD8,146,of course youll have the ser and estar verbs d...,1.0,Software,0.009863,[],[]
761600,B017Y5QV2Y,163,watch on app my 3 yr old loves blippi,5.0,Software,0.041220,[],[]