# ASC Phase 2 — TRAIN ONLY

Flow:

```text
load final_train_no_leakage
→ load gold_test_standardized
→ load model ASC phase 1
→ fine-tune tiếp phase 2
→ evaluate gold test
→ save model phase 2
```

## 1. Install libraries

In [1]:
!pip -q install datasets transformers accelerate evaluate scikit-learn sentencepiece

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 4.5 MB/s eta 0:00:00

## 2. Mount Drive + Config

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os
import json
from pathlib import Path

RANDOM_SEED = 2026
EPOCHS=3
MAX_LENGTH = 192
BATCH_SIZE = 32
GRAD_ACCUM = 2        # effective batch size = 64
EPOCHS = 3
LR = 2e-5
WARMUP_RATIO = 0.1
PROJECT_DIR = "/content/drive/MyDrive/asc_phase2"
OUTPUT_DIR = f"{PROJECT_DIR}/outputs"

# Data đã xử lý sẵn
FINAL_TRAIN_PATH = f"{OUTPUT_DIR}/final_train_no_leakage"
GOLD_TEST_STD_PATH = f"{OUTPUT_DIR}/gold_test_standardized"

# Model đã train phase 1
PHASE1_MODEL_DIR = f"{PROJECT_DIR}/asc_teacher_phase1/asc_teacher_phase1"

# Output phase 2

CHECKPOINT_DIR = '/content/asc_phase2_ckpt'
DRIVE_CKPT_DIR = f'{PROJECT_DIR}/asc_phase2_checkpoints'
MODEL_SAVE_DIR = f'{PROJECT_DIR}/asc_phase2_model'
TEST_METRICS_PATH = f"{OUTPUT_DIR}/gold_test_metrics_train_only.json"

os.makedirs(MODEL_SAVE_DIR, exist_ok=True)

print("FINAL_TRAIN_PATH:", FINAL_TRAIN_PATH)
print("GOLD_TEST_STD_PATH:", GOLD_TEST_STD_PATH)
print("PHASE1_MODEL_DIR:", PHASE1_MODEL_DIR)
print("MODEL_SAVE_DIR:", MODEL_SAVE_DIR)

for p in [FINAL_TRAIN_PATH, GOLD_TEST_STD_PATH, PHASE1_MODEL_DIR]:
    print(p, "OK" if os.path.exists(p) else "MISSING")

Mounted at /content/drive
FINAL_TRAIN_PATH: /content/drive/MyDrive/asc_phase2/outputs/final_train_no_leakage
GOLD_TEST_STD_PATH: /content/drive/MyDrive/asc_phase2/outputs/gold_test_standardized
PHASE1_MODEL_DIR: /content/drive/MyDrive/asc_phase2/asc_teacher_phase1/asc_teacher_phase1
MODEL_DIR: /content/drive/MyDrive/asc_phase2/roberta_asc_phase2_finetuned
/content/drive/MyDrive/asc_phase2/outputs/final_train_no_leakage OK
/content/drive/MyDrive/asc_phase2/outputs/gold_test_standardized OK
/content/drive/MyDrive/asc_phase2/asc_teacher_phase1/asc_teacher_phase1 OK

## 3. Check phase 1 model files

In [4]:
required_phase1_files = [
    "config.json",
    "model.safetensors",
    "tokenizer.json",
    "tokenizer_config.json",
]

for fn in required_phase1_files:
    p = os.path.join(PHASE1_MODEL_DIR, fn)
    print(fn, "OK" if os.path.exists(p) else "MISSING", p)

config.json OK /content/drive/MyDrive/asc_phase2/asc_teacher_phase1/asc_teacher_phase1/config.json
model.safetensors OK /content/drive/MyDrive/asc_phase2/asc_teacher_phase1/asc_teacher_phase1/model.safetensors
tokenizer.json OK /content/drive/MyDrive/asc_phase2/asc_teacher_phase1/asc_teacher_phase1/tokenizer.json
tokenizer_config.json OK /content/drive/MyDrive/asc_phase2/asc_teacher_phase1/asc_teacher_phase1/tokenizer_config.json

## 4. Load processed train/test dataset

In [5]:
from datasets import load_dataset, DatasetDict

hf_data = load_dataset(
    "parquet",
    data_files={
        "train": f"{FINAL_TRAIN_PATH}/*.parquet",
        "test": f"{GOLD_TEST_STD_PATH}/*.parquet",
    },
)

print(hf_data)
print(hf_data["train"][0])
print(hf_data["test"][0])

Generating train split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['sample_key', 'category_name', 'sentence', 'aspect', 'label', 'label_id'],
        num_rows: 2000001
    })
    test: Dataset({
        features: ['sample_key', 'category_name', 'sentence', 'aspect', 'label', 'label_id'],
        num_rows: 681
    })
})
{'sample_key': 'd855097003a11944c28803ddb05078c880b794c9356b9e5c7b002bc448272e29', 'category_name': 'kindle_store', 'sentence': 'most of the recipes are too long for me im not that ambitious', 'aspect': 'recipes', 'label': 'negative', 'label_id': 0}
{'sample_key': '00a37fbba165be86f2b841361d3cb6ee2dcc8565c7bf4fb2cf69b6be3825e72d', 'category_name': 'gold_test', 'sentence': 'durable quality seat covering replaced four bar seat covers with these and they look like new', 'aspect': 'quality', 'label': 'positive', 'label_id': 2}

## 5. Chuẩn hóa input cho model

In [6]:
def to_model_example(ex):
    return {
        "sentence": str(ex["sentence"]),
        "aspect": str(ex["aspect"]),
        "labels": int(ex["label_id"]),
    }

train_hf = hf_data["train"].map(
    to_model_example,
    remove_columns=hf_data["train"].column_names,
)

test_hf = hf_data["test"].map(
    to_model_example,
    remove_columns=hf_data["test"].column_names,
)

dataset = DatasetDict({
    "train": train_hf,
    "test": test_hf,
})

dataset

Map:   0%|          | 0/2000001 [00:00<?, ? examples/s]

Map:   0%|          | 0/681 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['sentence', 'aspect', 'labels'],
        num_rows: 2000001
    })
    test: Dataset({
        features: ['sentence', 'aspect', 'labels'],
        num_rows: 681
    })
})

## 6. Train/validation split

In [8]:
from datasets import ClassLabel, DatasetDict

# Define the ClassLabel feature for 'labels'
label_features = ClassLabel(names=["negative", "neutral", "positive"])

# Cast the 'labels' column in the training dataset to ClassLabel
dataset["train"] = dataset["train"].cast_column("labels", label_features)

split = dataset["train"].train_test_split(
    test_size=0.02,
    seed=RANDOM_SEED,
    stratify_by_column="labels",
)

dataset = DatasetDict({
    "train": split["train"],
    "validation": split["test"],
    "test": dataset["test"],
})

dataset

Casting the dataset:   0%|          | 0/2000001 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['sentence', 'aspect', 'labels'],
        num_rows: 1960000
    })
    validation: Dataset({
        features: ['sentence', 'aspect', 'labels'],
        num_rows: 40001
    })
    test: Dataset({
        features: ['sentence', 'aspect', 'labels'],
        num_rows: 681
    })
})

## 7. Tokenize bằng tokenizer phase 1

In [ ]:
from transformers import AutoTokenizer
from datasets import Dataset

tokenizer = AutoTokenizer.from_pretrained(PHASE1_MODEL_DIR, use_fast=True)
special_tokens = {'additional_special_tokens': ['[ASP]', '[/ASP]']}
tokenizer.add_special_tokens(special_tokens)

train_dataset = Dataset.from_pandas(df_train[['text', 'label']], preserve_index=False)
test_dataset  = Dataset.from_pandas(df_test[['text', 'label']], preserve_index=False)


def tokenize_fn(batch):
    return tokenizer(
        batch['text'],
        truncation=True,
        max_length=MAX_LENGTH,
        padding=False,
    )


train_dataset = train_dataset.map(tokenize_fn, batched=True, batch_size=4096, remove_columns=['text'])
test_dataset  = test_dataset.map(tokenize_fn, batched=True, batch_size=4096, remove_columns=['text'])

train_dataset.set_format('torch')
test_dataset.set_format('torch')

print(f'Train dataset: {len(train_dataset):,}')
print(f'Test dataset:  {len(test_dataset):,}')
print(f'Features: {train_dataset.features}')

Map:   0%|          | 0/1960000 [00:00<?, ? examples/s]

Map:   0%|          | 0/40001 [00:00<?, ? examples/s]

Map:   0%|          | 0/681 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['labels', 'input_ids', 'attention_mask'],
        num_rows: 1960000
    })
    validation: Dataset({
        features: ['labels', 'input_ids', 'attention_mask'],
        num_rows: 40001
    })
    test: Dataset({
        features: ['labels', 'input_ids', 'attention_mask'],
        num_rows: 681
    })
})

## 8. Train config — chỉnh để kịp 3h30

In [10]:
# Nếu Colab chỉ còn ~3h30, nên để max_steps thay vì train hết 1 epoch.
# Bạn có thể tăng/giảm MAX_STEPS tùy GPU:
# - T4: thử 6000-10000
# - L4/A100: có thể cao hơn
# Nếu muốn chạy full 1 epoch, set MAX_STEPS = -1

# MAX_STEPS = -1
# EVAL_STEPS = 1000
# SAVE_STEPS = 1000

# PER_DEVICE_TRAIN_BATCH_SIZE = 8
# GRADIENT_ACCUMULATION_STEPS = 4

# LEARNING_RATE = 1e-5

## 9. Fine-tune tiếp từ ASC phase 1

In [ ]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    PHASE1_MODEL_DIR,
    num_labels=3,
)
model.resize_token_embeddings(len(tokenizer))

n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f'Trainable params: {n_params / 1e6:.1f}M')

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.output.LayerNorm.weight', 'roberta.encoder.layer.4.attention.output.LayerNorm.bias', 'roberta.encoder.layer.4.output.LayerNorm.weight', 'roberta.encoder.layer.4.output.LayerNorm.bias', 'roberta.encoder.layer.5.attention.output.LayerNorm.weight', 'roberta.encoder.layer.5.attention.output.LayerNorm.bias', 'roberta.encoder.layer.5.output.LayerNorm.weight', 'roberta.encoder.layer.5.output.LayerNorm.bias', 'roberta.encoder.layer.6.attention.output.LayerNorm.weight', 'roberta.encoder.layer.6.attention.output.LayerNorm.bias', 'roberta.encoder.layer.6.output.LayerNorm.weight', 'roberta.encoder.layer.6.output.LayerNorm.bias', 'roberta.encoder.layer.7.attention.output.LayerNorm.weight', 'roberta.encoder.layer.7.attention.output.LayerNorm.bias', 'roberta.encoder.layer.7.output.LayerNorm.weight', 'roberta.encoder.layer.7.output.LayerNorm.bias', 'roberta.encoder.layer.8.attention.output.LayerNorm.weight', 'roberta.encoder.layer.8.attention.output.LayerNorm.bias', 'roberta.encoder.layer.8.output.LayerNorm.weight', 'roberta.encoder.layer.8.output.LayerNorm.bias', 'roberta.encoder.layer.9.attention.output.LayerNorm.weight', 'roberta.encoder.layer.9.attention.output.LayerNorm.bias', 'roberta.encoder.layer.9.output.LayerNorm.weight', 'roberta.encoder.layer.9.output.LayerNorm.bias', 'roberta.encoder.layer.10.attention.output.LayerNorm.weight', 'roberta.encoder.layer.10.attention.output.LayerNorm.bias', 'roberta.encoder.layer.10.output.LayerNorm.weight', 'roberta.encoder.layer.10.output.LayerNorm.bias', 'roberta.encoder.layer.11.attention.output.LayerNorm.weight', 'roberta.encoder.layer.11.attention.output.LayerNorm.bias', 'roberta.encoder.layer.11.output.LayerNorm.weight', 'roberta.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.beta', 'roberta.embeddings.LayerNorm.gamma', 'roberta.encoder.layer.0.attention.output.LayerNorm.beta', 'roberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.0.output.LayerNorm.beta', 'roberta.encoder.layer.0.output.LayerNorm.gamma', 'roberta.encoder.layer.1.attention.output.LayerNorm.beta', 'roberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.1.output.LayerNorm.beta', 'roberta.encoder.layer.1.output.LayerNorm.gamma', 'roberta.encoder.layer.2.attention.output.LayerNorm.beta', 'roberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.2.output.LayerNorm.beta', 'roberta.encoder.layer.2.output.LayerNorm.gamma', 'roberta.encoder.layer.3.attention.output.LayerNorm.beta', 'roberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.3.output.LayerNorm.beta', 'roberta.encoder.layer.3.output.LayerNorm.gamma', 'roberta.encoder.layer.4.attention.output.LayerNorm.beta', 'roberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.4.output.LayerNorm.beta', 'roberta.encoder.layer.4.output.LayerNorm.gamma', 'roberta.encoder.layer.5.attention.output.LayerNorm.beta', 'roberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.5.output.LayerNorm.beta', 'roberta.encoder.layer.5.output.LayerNorm.gamma', 'roberta.encoder.layer.6.attention.output.LayerNorm.beta', 'roberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.6.output.LayerNorm.beta', 'roberta.encoder.layer.6.output.LayerNorm.gamma', 'roberta.encoder.layer.7.attention.output.LayerNorm.beta', 'roberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.7.output.LayerNorm.beta', 'roberta.encoder.layer.7.output.LayerNorm.gamma', 'roberta.encoder.layer.8.attention.output.LayerNorm.beta', 'roberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.8.output.LayerNorm.beta', 'roberta.encoder.layer.8.output.LayerNorm.gamma', 'roberta.encoder.layer.9.attention.output.LayerNorm.beta', 'roberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.9.output.LayerNorm.beta', 'roberta.encoder.layer.9.output.LayerNorm.gamma', 'roberta.encoder.layer.10.attention.output.LayerNorm.beta', 'roberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.10.output.LayerNorm.beta', 'roberta.encoder.layer.10.output.LayerNorm.gamma', 'roberta.encoder.layer.11.attention.output.LayerNorm.beta', 'roberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.11.output.LayerNorm.beta', 'roberta.encoder.layer.11.output.LayerNorm.gamma'].

TrainOutput(global_step=61250, training_loss=0.21781736790404027, metrics={'train_runtime': 15298.0577, 'train_samples_per_second': 128.121, 'train_steps_per_second': 4.004, 'total_flos': 5.232076912105142e+16, 'train_loss': 0.21781736790404027, 'epoch': 1.0})

## 11. Evaluate gold test

In [ ]:
import shutil
import glob
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from transformers import TrainingArguments, Trainer, TrainerCallback


def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    acc = accuracy_score(labels, preds)
    p_macro, r_macro, f1_macro, _ = precision_recall_fscore_support(
        labels, preds, average='macro'
    )
    p_w, r_w, f1_w, _ = precision_recall_fscore_support(
        labels, preds, average='weighted'
    )
    return {
        'accuracy': acc,
        'f1_macro': f1_macro,
        'precision_macro': p_macro,
        'recall_macro': r_macro,
        'f1_weighted': f1_w,
        'precision_weighted': p_w,
        'recall_weighted': r_w,
    }


class DriveCheckpointCallback(TrainerCallback):
    """Copy checkpoint lên Drive sau mỗi lần save (mỗi epoch)."""

    def on_save(self, args, state, control, **kwargs):
        src = os.path.join(args.output_dir, f'checkpoint-{state.global_step}')
        if not os.path.isdir(src):
            return
        dst = os.path.join(DRIVE_CKPT_DIR, f'checkpoint-{state.global_step}')
        if os.path.exists(dst):
            shutil.rmtree(dst)
        shutil.copytree(src, dst)
        print(f'\n>>> Checkpoint copied to Drive: {dst}')

        # Giữ tối đa 2 checkpoint trên Drive
        ckpts = sorted(glob.glob(os.path.join(DRIVE_CKPT_DIR, 'checkpoint-*')))
        while len(ckpts) > 2:
            shutil.rmtree(ckpts.pop(0))
            print(f'>>> Removed old Drive checkpoint')



training_args = TrainingArguments(
    output_dir=CHECKPOINT_DIR,
    num_train_epochs=EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=64,
    gradient_accumulation_steps=GRAD_ACCUM,
    learning_rate=LR,
    warmup_ratio=WARMUP_RATIO,
    weight_decay=0.01,
    eval_strategy='epoch',
    save_strategy='epoch',
    load_best_model_at_end=True,
    metric_for_best_model='f1_macro',
    greater_is_better=True,
    save_total_limit=2,
    fp16=True,
    dataloader_num_workers=2,
    dataloader_pin_memory=True,
    logging_steps=500,
    seed=RANDOM_SEED,
    report_to='none',
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
    callbacks=[DriveCheckpointCallback()],
)

print(f'Steps/epoch: {len(train_dataset) // (BATCH_SIZE * GRAD_ACCUM):,}')
print(f'Total steps:  {len(train_dataset) // (BATCH_SIZE * GRAD_ACCUM) * EPOCHS:,}')
print(f'Checkpoints sẽ được lưu trên Drive: {DRIVE_CKPT_DIR}')

In [ ]:
# Auto-detect checkpoint từ Drive (hỗ trợ đổi tài khoản Colab)
resume_ckpt = None
drive_ckpts = sorted(glob.glob(os.path.join(DRIVE_CKPT_DIR, 'checkpoint-*')))

if drive_ckpts:
    latest_drive = drive_ckpts[-1]
    local_ckpt = os.path.join(CHECKPOINT_DIR, os.path.basename(latest_drive))

    if not os.path.exists(local_ckpt):
        print(f'Restoring checkpoint from Drive: {latest_drive}')
        os.makedirs(CHECKPOINT_DIR, exist_ok=True)
        shutil.copytree(latest_drive, local_ckpt)
        print(f'  -> Copied to: {local_ckpt}')

    resume_ckpt = local_ckpt
    print(f'Resuming from: {resume_ckpt}')
else:
    print('No checkpoint found. Training from scratch.')

trainer.train(resume_from_checkpoint=resume_ckpt)

In [ ]:
results = trainer.evaluate()
print('  BENCHMARK RESULTS — GOLD TEST SET')
for k, v in sorted(results.items()):
    if k.startswith('eval_') and k != 'eval_runtime' and 'per_second' not in k:
        print(f'  {k.replace("eval_", ""):25s} : {v:.4f}')

{'eval_loss': 1.2020106315612793, 'eval_accuracy': 0.8619676945668135, 'eval_precision_macro': 0.8164414636876658, 'eval_recall_macro': 0.6213288133199145, 'eval_f1_macro': 0.637060708320551, 'eval_f1_weighted': 0.849033035367976, 'eval_runtime': 0.9969, 'eval_samples_per_second': 683.099, 'eval_steps_per_second': 22.068, 'epoch': 1.0}
Saved metrics: /content/drive/MyDrive/asc_phase2/outputs/gold_test_metrics_train_only.json

## 12. Classification report + confusion matrix

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
LABEL_NAMES = ['negative', 'neutral', 'positive']
preds_output = trainer.predict(test_dataset)
y_pred = np.argmax(preds_output.predictions, axis=-1)
y_true = preds_output.label_ids

print('Classification Report:')
print(classification_report(y_true, y_pred, target_names=LABEL_NAMES, digits=4))

print('\nConfusion Matrix:')
cm = confusion_matrix(y_true, y_pred)
cm_df = pd.DataFrame(
    cm,
    index=[f'true_{n}' for n in LABEL_NAMES],
    columns=[f'pred_{n}' for n in LABEL_NAMES],
)
print(cm_df.to_string())

              precision    recall  f1-score   support

    negative     0.8117    0.8341    0.8227       217
     neutral     0.7500    0.1034    0.1818        29
    positive     0.8877    0.9264    0.9066       435

    accuracy                         0.8620       681
   macro avg     0.8164    0.6213    0.6371       681
weighted avg     0.8576    0.8620    0.8490       681

          negative  neutral  positive
negative       181        0        36
neutral         11        3        15
positive        31        1       403

## 13. Save final model

In [ ]:
os.makedirs(MODEL_SAVE_DIR, exist_ok=True)
trainer.save_model(MODEL_SAVE_DIR)
tokenizer.save_pretrained(MODEL_SAVE_DIR)
print(f'Model saved to {MODEL_SAVE_DIR}')